version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: iot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  fastapi_backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres/iot
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./app:/app

  # worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   command: ['celery', '-A', 'backend.celery_worker.celery', 'worker', '-l', 'INFO']
  #   depends_on:
  #     - postgres
  #     - redis
  #     - fastapi_backend

  # beat:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   command: celery -A backend.main.app beat -l info

  # celery:
  #   build: .
  #   command: celery -A main.celery worker -l info
  #   environment:
  #     DATABASE_URL: postgresql://your_db_user:your_db_password@postgres:5432/your_db_name
  #     REDIS_URL: redis://redis:6379/0
  #   depends_on:
  #     - postgres
  #     - redis
  #     - backend
  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data



volumes:
  postgres_data:
  redis-data:
